apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: prajwaldevops01/eks-app:v0.0.1
        ports:
        - containerPort: 80